actions:
  site:
    type: access
    label: Site                    # 站点权限
  admin:
    type: access
    label: Admin                   # 管理权限
  admin.pages:
    type: access
    label: Pages                   # 页面管理权限
  admin.users:
    type: access
    label: User Accounts           # 用户账户管理权限

types:
  default:
    type: access                   # 默认类型，定义为访问权限

  crud:
    type: compact                  # 类型为精简模式
    letters:                       # 字母操作映射
      c:
        action: create             # 动作：创建
        label: PLUGIN_ADMIN.CREATE # 标签：创建
      r:
        action: read               # 动作：读取
        label: PLUGIN_ADMIN.READ   # 标签：读取
      u:
        action: update             # 动作：更新
        label: PLUGIN_ADMIN.UPDATE # 标签：更新
      d:
        action: delete             # 动作：删除
        label: PLUGIN_ADMIN.DELETE # 标签：删除

  crudp:
    type: crud                     # 基于 CRUD 类型
    letters:                       # 字母操作映射
      p:
        action: publish            # 动作：发布
        label: PLUGIN_ADMIN.PUBLISH # 标签：发布

  crudl:
    type: crud                     # 基于 CRUD 类型
    letters:                       # 字母操作映射
      l:
        action: list               # 动作：列出
        label: PLUGIN_ADMIN.LIST   # 标签：列出

  crudpl:
    type: crud                     # 基于 CRUD 类型
    use:                           # 使用已定义的操作类型
      - crudp                      # 包含发布权限
      - crudl                      # 包含列出权限
