title: erelcms                                 # 网站名称
default_lang: zh                            # 网站的默认语言（可能被主题使用）

author:
  name: John Appleseed                      # 默认作者名称
  email: 'john@example.com'                 # 默认作者邮箱

taxonomies: [category,tag]                  # 分类法类型的任意列表

metadata:
  description: 'erelcms默认描述'               # 网站描述

summary:
  enabled: true                             # 启用或禁用页面摘要
  format: short                             # long = 忽略摘要分隔符；short = 使用分隔符首次出现的位置或指定大小
  size: 300                                 # 摘要的最大长度（字符数）
  delimiter: ===                            # 摘要分隔符

redirects:
#  '/redirect-test': '/'                    # 将 /redirect-test 重定向到首页
#  '/old/(.*)': '/new/$1'                   # 将 /old/my-page 重定向到 /new/my-page

routes:
#  '/something/else': '/blog/sample-3'      # 将 /blog/sample-3 的别名设置为 /something/else
#  '/new/(.*)': '/blog/$1'                  # 将 /new/my-page 的 URL 正则映射到 /blog/my-page 路由

blog:
  route: '/news'                            # 自定义值（可通过 site.blog.route 访问）

#menu:                                      # 菜单示例
#    - text: Source
#      icon: github
#      url: https://github.com/getgrav/grav
#    - icon: twitter
#      url: http://twitter.com/getgrav
