absolute_urls: false                             # 为 `base_url` 设置绝对或相对 URL
timezone: ''                                     # 有效值：http://php.net/manual/en/timezones.php
default_locale:                                  # 默认语言环境（默认为系统设置）
param_sep: ':'                                   # 参数分隔符，Windows 上的 Apache 使用 ';'
wrapped_site: false                              # 供主题/插件判断 Grav 是否被其他平台包装
reverse_proxy_setup: false                       # 在反向代理场景下，代理和 Web 服务器端口不同
force_ssl: false                                 # 如果启用，强制通过 HTTPS 访问 Grav（注意：不是理想的解决方案）
force_lowercase_urls: true                       # 如果要支持混合大小写 URL，将此项设为 false
custom_base_url: ''                              # 手动设置 base_url，例如 http://yoursite.com/yourpath
username_regex: '^[a-z0-9_-]{3,16}$'             # 仅允许小写字符、数字、短划线、下划线。长度 3-16 个字符
pwd_regex: '^[a-z0-9_-]{3,16}$'                  # 仅允许小写字符、数字、短划线、下划线。长度 3-16 个字符
intl_enabled: true                               # PHP 国际化扩展（mod_intl）的特殊逻辑
http_x_forwarded:                                # 各种 HTTP_X_FORWARD 标头的配置选项
  protocol: true
  host: false
  port: true
  ip: true

languages:
  supported:
    - zh
    - en                                  # 支持的语言列表，例如：[en, fr, de]
  default_lang: zh                                 # 默认为第一个支持的语言。必须是支持的语言之一
  include_default_lang: true                     # 在所有 URL 中包含默认语言前缀
  include_default_lang_file_extension: true      # 如果为 true，在文件扩展名中包含默认语言代码：default.en.md
  translations: true                             # 如果为 false，使用翻译键而不是翻译字符串
  translations_fallback: true                    # 如果活动语言不存在，则回退到支持的翻译
  session_store_active: false                    # 在会话中存储活动语言
  http_accept_language: false                    # 尝试根据浏览器中的 http_accept_language 标头设置语言
  override_locale: false                         # 使用语言特定的语言环境覆盖默认或系统语言环境
  content_fallback: {}                           # 自定义语言回退，例如：{fr: ['fr', 'en']}
  pages_fallback_only: false                     # 已废弃：使用 `content_fallback` 代替
  debug: false                                   # 调试语言检测

home:
  alias: '/home'                                 # 主页面的默认路径，例如 /
  hide_in_urls: false                            # 在 URL 中隐藏主路由

pages:
  type: regular                                  # 实验性：页面类型：regular 或 flex
  dirs: ['page://']                              # 高级功能，允许多个页面路径
  theme: quark                                   # 默认主题（默认为 "quark" 主题）
  order:
    by: default                                  # 页面排序方式："default"、"alpha" 或 "date"
    dir: asc                                     # 默认排序方向："asc" 或 "desc"
  list:
    count: 20                                    # 每页默认的项目数量
  dateformat:
    default:                                     # Grav 在 `date:` 字段中预期的默认日期格式
    short: 'jS M Y'                              # 短日期格式
    long: 'F jS \a\t g:ia'                       # 长日期格式
  publish_dates: true                            # 基于日期自动发布/取消发布
  process:
    markdown: true                               # 处理 Markdown
    twig: false                                  # 处理 Twig
  twig_first: false                              # 同时处理 Markdown 和 Twig 时优先处理 Twig
  never_cache_twig: false                        # 仅缓存内容，从不缓存 Twig 处理的内容（与 `twig_first: true` 不兼容）
  events:
    page: true                                   # 启用页面级别事件
    twig: true                                   # 启用 Twig 级别事件
  markdown:
    extra: false                                 # 启用对 Markdown Extra 的支持（默认 GFM）
    auto_line_breaks: false                      # 启用自动换行
    auto_url_links: false                        # 启用自动 HTML 链接
    escape_markup: false                         # 将标记转换为实体
    special_chars:                               # 自动转换为实体的特殊字符列表
      '>': 'gt'
      '<': 'lt'
    valid_link_attributes:                       # Markdown 链接中允许的属性
      - rel
      - target
      - id
      - class
      - classes
  types: [html,htm,xml,txt,json,rss,atom]        # 有效页面类型的列表
  append_url_extension: ''                       # 在页面 URL 中附加页面扩展名（例如：'.html' 结果为 /path/page.html）
  expires: 604800                                # 页面过期时间（秒）（604800 秒 = 7 天）
  cache_control:                                 # 可以为空（无设置）或有效的 `cache-control` 文本值
  last_modified: false                           # 基于文件修改时间戳设置最后修改日期标头
  etag: true                                     # 设置 etag 标头标签
  vary_accept_encoding: false                    # 添加 `Vary: Accept-Encoding` 标头
  redirect_default_code: 302                     # 重定向时使用的默认代码：301|302|303
  redirect_trailing_slash: 1                     # 始终用重定向代码 0|1|301|302 重定向尾部斜杠（0：不重定向，1：使用默认代码）
  redirect_default_route: 0                      # 始终使用代码 0|1|301|302 重定向到页面的默认路由，同时删除 .htm 和 .html 扩展名
  ignore_files: [.DS_Store]                      # 在页面中忽略的文件
  ignore_folders: [.git, .idea]                  # 在页面中忽略的文件夹
  ignore_hidden: true                            # 忽略所有隐藏文件和文件夹
  hide_empty_folders: false                      # 如果文件夹没有 .md 文件，是否隐藏
  url_taxonomy_filters: true                     # 为页面集合启用基于 URL 的自动分类过滤器
  frontmatter:
    process_twig: false                          # 是否处理 frontmatter 中的 Twig 变量？
    ignore_fields: ['form','forms']              # 可能包含 Twig 变量并且不应被处理的字段

cache:
  enabled: true                                  # 设置为 true 以启用缓存
  check:
    method: file                                 # 检查页面更新的方法：file|folder|hash|none
  driver: auto                                   # 驱动类型：auto|file|apcu|memcache|wincache
  prefix: 'g'                                    # 缓存前缀字符串（防止缓存冲突）
  purge_at: '0 4 * * *'                          # 多久清除一次旧文件缓存（使用新调度程序）
  clear_at: '0 3 * * *'                          # 多久清除一次缓存（使用新调度程序）
  clear_job_type: 'standard'                     # 处理计划清除作业时清除的类型 `standard`|`all`
  clear_images_by_default: false                 # 默认情况下 Grav 不会包含处理过的图像进行缓存清除，可以启用
  cli_compatibility: false                       # 确保仅使用非易失性驱动程序（file、redis、memcache 等）
  lifetime: 604800                               # 缓存数据的生命周期（秒）（0 = 无限）
  gzip: false                                    # GZip 压缩页面输出
  allow_webserver_gzip: false                    # 如果为 true，`content-encoding: identity` 但在 `onShutDown()` 事件前连接未关闭
  redis:
    socket: false                                # Redis Unix 套接字的路径（例如 /var/run/redis/redis.sock），false = 使用服务器和端口连接
    password:                                    # 可选密码
    database:                                    # 可选数据库 ID

twig:
  cache: true                                    # 设置为 true 以启用 Twig 缓存
  debug: true                                    # 启用 Twig 调试
  auto_reload: true                              # 在更改时刷新缓存
  autoescape: true                               # 自动转义 Twig 变量（已废弃，在严格模式下始终启用）
  undefined_functions: true                      # 允许未定义的函数
  undefined_filters: true                        # 允许未定义的过滤器
  safe_functions: []                             # 允许作为 Twig 函数使用的 PHP 函数列表
  safe_filters: []                               # 允许作为 Twig 过滤器使用的 PHP 函数列表
  umask_fix: false                               # 默认情况下，Twig 创建缓存文件为 755，此修复将其更改为 775

assets:                                          # 资产管理器 (JS, CSS) 的配置
  css_pipeline: false                            # CSS 管道是将多个 CSS 资源统一为一个文件
  css_pipeline_include_externals: true           # 默认情况下包含外部 URL
  css_pipeline_before_excludes: true             # 在任何排除的文件之前渲染管道
  css_minify: true                               # 在管道化期间最小化 CSS
  css_minify_windows: false                      # 针对 Windows 平台的最小化覆盖。默认情况下为 false
  css_rewrite: true                              # 在管道化期间重写任何 CSS 相对 URL
  js_pipeline: false                             # JS 管道是将多个 JS 资源统一为一个文件
  js_pipeline_include_externals: true            # 默认情况下包含外部 URL
  js_pipeline_before_excludes: true              # 在任何排除的文件之前渲染管道
  js_module_pipeline: false                      # JS 模块管道是将多个 JS 模块资源统一为一个文件
  js_module_pipeline_include_externals: true     # 默认情况下包含外部 URL
  js_module_pipeline_before_excludes: true       # 在任何排除的文件之前渲染管道
  js_minify: true                                # 在管道化期间最小化 JS
  enable_asset_timestamp: false                  # 启用资产时间戳
  enable_asset_sri: false                        # 启用资产完整性 (SRI)
  collections:
    jquery: system://assets/jquery/jquery-3.x.min.js  # jQuery 的路径集合

errors:
  display: 0                                     # 显示 (1) 完整回溯 | (0) 简单错误 | (-1) 系统错误
  log: true                                      # 将错误记录到 /logs 文件夹

log:
  handler: file                                  # 日志处理程序。当前支持：file | syslog
  syslog:
    facility: local6                             # Syslog 输出设施
    tag: grav                                    # Syslog 标签。默认："grav"

debugger:
  enabled: false                                 # 启用 Grav 调试器和以下设置
  provider: clockwork                            # 调试器提供程序：debugbar | clockwork
  censored: false                                # 屏蔽可能敏感的信息（POST 参数、Cookies、文件、日志消息中的大多数数组/对象数据）
  shutdown:
    close_connection: true                       # 在调用 onShutdown() 之前关闭连接。调试时设置为 false

images:
  default_image_quality: 85                      # 重采样图像时的默认图像质量 (85%)
  cache_all: false                               # 默认缓存所有图像
  cache_perms: '0755'                            # 必须用引号括起来！缓存文件夹的默认权限。通常为 '0755' 或 '0775'
  debug: false                                   # 在图像上显示叠加信息以指示像素深度（例如 Retina 图像）
  auto_fix_orientation: true                     # 根据 Exif 数据自动修正图像方向
  seofriendly: false                             # SEO 友好的已处理图像名称
  cls:                                           # 累积布局偏移 (CLS) 优化选项：https://web.dev/optimize-cls/
    auto_sizes: false                            # 自动为图像添加高度/宽度
    aspect_ratio: false                          # 使用宽高比样式保留空间
    retina_scale: 1                              # 缩放以调整高分辨率屏幕的自动大小处理
  defaults:
    loading: auto                                # 让浏览器选择加载方式 [auto|lazy|eager]
    decoding: auto                               # 让浏览器选择解码方式 [auto|sync|async]
    fetchpriority: auto                          # 让浏览器选择获取优先级 [auto|high|low]
  watermark:
    image: 'system://images/watermark.png'       # 水印图像的路径
    position_y: 'center'                         # top|center|bottom
    position_x: 'center'                         # left|center|right
    scale: 33                                    # 水印缩放百分比
    watermark_all: false                         # 自动为所有图像添加水印

media:
  enable_media_timestamp: false                  # 启用媒体时间戳
  unsupported_inline_types: []                   # 不支持内嵌显示的媒体类型数组
  allowed_fallback_types: []                     # 如果通过页面路由访问，允许的媒体类型数组
  auto_metadata_exif: false                      # 尽可能从 Exif 数据自动创建元数据文件

session:
  enabled: true                                  # 启用会话支持
  initialize: true                               # 从 Grav 初始化会话（如果为 false，则需要插件启动会话）
  timeout: 1800                                  # 超时时间（秒）
  name: grav-site                                # 会话 Cookie 的名称前缀。仅使用字母、数字、短划线或下划线。不使用点
  uniqueness: path                               # 会话是否基于 `path` 或 `security.salt`
  secure: false                                  # 设置会话为安全模式。如果为 true，表示该 Cookie 必须通过加密传输使用。仅在完全使用 HTTPS 的站点启用
  secure_https: true                             # 在 HTTPS 上设置会话安全，但在 HTTP 上不设置。如果站点在 HTTP 和 HTTPS 之间切换，则设置为 false
  httponly: true                                 # 将会话设置为仅 HTTP。如果为 true，表示 Cookie 只能通过 HTTP 使用，JavaScript 不允许修改
  samesite: Lax                                  # 设置会话 SameSite 值。可能的值为 Lax, Strict 和 None
  split: true                                    # 会话在站点和插件（例如管理插件）之间应独立
  domain:                                        # 会话使用的域
  path:                                          # 会话使用的路径

gpm:
  releases: stable                               # 设置为 'stable' 或 'testing'
  official_gpm_only: true                        # 默认情况下，GPM 直接安装仅允许通过官方 GPM 代理的 URL 以确保安全性

http:
  method: auto                                   # 设置为 'curl', 'fopen' 或 'auto'. 'auto' 将优先尝试 fopen，如果不可用则使用 cURL
  enable_proxy: true                             # 启用代理服务器配置
  proxy_url:                                     # 配置 GPM 的手动代理 URL（例如 127.0.0.1:3128）
  proxy_cert_path:                               # 代理证书文件夹的本地路径，包含 PEM 文件
  concurrent_connections: 5                      # 启用多路复用时的并发 HTTP 连接数
  verify_peer: true                              # 启用/禁用对等证书的 SSL 验证
  verify_host: true                              # 启用/禁用主机证书的 SSL 验证

accounts:
  type: regular                                  # 实验性：账户类型：regular 或 flex
  storage: file                                  # 实验性：Flex 存储类型：file 或 folder
  avatar: gravatar                               # 头像生成器 [multiavatar|gravatar]

flex:
  cache:
    index:
      enabled: true                              # 设置为 true 以启用 Flex 索引缓存。用于缓存文件中的时间戳
      lifetime: 60                               # 缓存索引的生命周期（秒）（0 = 无限）
    object:
      enabled: true                              # 设置为 true 以启用 Flex 对象缓存。用于缓存对象数据
      lifetime: 600                              # 缓存对象的生命周期（秒）（0 = 无限）
    render:
      enabled: true                              # 设置为 true 以启用 Flex 渲染缓存。用于缓存渲染的输出
      lifetime: 600                              # 缓存 HTML 的生命周期（秒）（0 = 无限）

strict_mode:
  yaml_compat: false                             # 设置为 true 以启用 YAML 向后兼容
  twig_compat: false                             # 设置为 true 以启用已废弃的 Twig 设置（autoescape: false）
  blueprint_compat: false                        # 设置为 true 以启用蓝图的向后兼容严格支持
